version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - build

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - build
